name: Editor and Publisher Docker Images

on:
  workflow_dispatch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKERLOGIN}}" -p="${{ secrets.DOCKERPASSWORD }}"
    - name: List Directory
      run: ls -alg
    - name: Build Editor Docker Image
      run: docker build . --file Editor/Dockerfile --tag ${{ secrets.DOCKERLOGIN}}/sky-editor:latest
    - name: Push Editor container to Docker Hub
      run: docker push ${{ secrets.DOCKERLOGIN}}/sky-editor
    - name: Build Publisher Docker Image
      run: docker build . --file Publisher/Dockerfile --tag ${{ secrets.DOCKERLOGIN}}/sky-publisher:latest
    - name: Push Publisher container to Docker Hub
      run: docker push ${{ secrets.DOCKERLOGIN}}/sky-publisher
